package api.arq.validator.dto;

public enum  ApiErroCodigo {
    JA_EXISTE, SENHAS_NAO_CONFEREM, SENHA_OU_USUARIO_INCORRETO,
    NAO_ENCONTRADO, EMPRESA_NAO_EXISTE, PERFIL_NAO_EXISTE,
    EXISTE_PARQUE_VINCULADO, PARQUE_EOLICO_NAO_EXISTE, MODELO_AERO_GERADOR_NAO_EXISTE,
    PONTOS_CURVA_REFERENCIA_VAZIO, EXISTE_AEROGERADOR_VINCULADO,
    EXISTE_CURVA_REFERENCIA_VINCULADA, EXISTE_TORRE_ANEMOMETRICA_VINCULADA
}
